spring:
  application:
    name: 'AppNameYml'
app:
  name: 'MyAppYml'
  description: "${app.name} is a Spring Boot application"

management:
  endpoints:
    web:
      exposure:
        include: '*'


ribbon:
  eureka:
    enabled: false
zuul:
  ignoredServices: '*'
  routes:
    proxy1:
      path: /proxy1/**
      url: forward:/?param=myProxy
    proxy2:
      path: /proxy2/**
      url: forward:/?param=proxy1
